[project]
name = "hexlet-code"
version = "0.1.0"
description = '''\"Mind Games" is a collection of five console games based on popular 
mobile brain training apps. Each game asks questions that require correct answers. 
After three correct answers, the game is completed; an incorrect answer ends the game and 
prompts you to play it again.'''
readme = "README.md"
authors = [
  { name = "Alexander Evseev" }
]
requires-python = ">=3.9"
dependencies = [
    "prompt>=0.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["brain_games"]

[dependency-groups]
dev = [
    "ruff>=0.15.22",
]

[project.scripts]
brain-games = "brain_games.scripts.brain_games:main"
brain-even = "brain_games.scripts.brain_even:main"
brain-calc = "brain_games.scripts.brain_calc:main"
brain-gcd = "brain_games.scripts.brain_gcd:main"
brain-prime = "brain_games.scripts.brain_prime:main"
brain-progression = "brain_games.scripts.brain_progression:main"
